pub const FIELD_AXIOMS: &[&str] = &[
    "=== FIELD AXIOMS ===",
    "For all a, b, c in R:",
    "",
    "CLOSURE",
    "  a+b in R; a*b in R",
    "",
    "COMMUTATIVITY",
    "  a+b = b+a",
    "  a*b = b*a",
    "",
    "ASSOCIATIVITY",
    "  (a+b)+c = a+(b+c)",
    "  (a*b)*c = a*(b*c)",
    "",
    "IDENTITY",
    "  a+0 = a  (additive id: 0)",
    "  a*1 = a  (mult id: 1)",
    "",
    "INVERSES",
    "  a+(-a) = 0",
    "  a*(1/a) = 1  (a not 0)",
    "",
    "DISTRIBUTIVITY",
    "  a*(b+c) = a*b + a*c",
];

pub const KEY_FORMULAS: &[&str] = &[
    "=== KEY FORMULAS ===",
    "",
    "SLOPE",
    "  m = (y2-y1)/(x2-x1)",
    "  m = rise/run",
    "",
    "LINEAR FORMS",
    "  Slope-intercept: y=mx+b",
    "  Point-slope:",
    "    y-y1 = m(x-x1)",
    "  Standard: Ax+By=C",
    "",
    "QUADRATIC FORMULA",
    "  ax^2+bx+c=0:",
    "  x=(-b+-sqrt(b^2-4ac))/2a",
    "",
    "DISCRIMINANT",
    "  D = b^2-4ac",
    "  D>0: 2 real roots",
    "  D=0: 1 real root",
    "  D<0: 2 complex roots",
    "",
    "VERTEX (h,k)",
    "  h = -b/(2a)",
    "  k = c - b^2/(4a)",
    "  Vertex form: a(x-h)^2+k",
    "",
    "COMPLETING THE SQUARE",
    "  ax^2+bx+c",
    "  = a(x+b/2a)^2+(c-b^2/4a)",
    "",
    "IMAGINARY UNIT",
    "  i = sqrt(-1)",
    "  i^2 = -1",
    "  Powers cycle: i,-1,-i,1",
];

pub const ALG_PROPERTIES: &[&str] = &[
    "=== ALGEBRAIC PROPS ===",
    "",
    "EQUALITY PROPERTIES",
    "  Reflexive:  a = a",
    "  Symmetric:  a=b => b=a",
    "  Transitive: a=b,b=c => a=c",
    "",
    "  Add Prop: a=b => a+c=b+c",
    "  Mult Prop: a=b => ac=bc",
    "  Subst: a=b => sub b for a",
    "",
    "ORDER PROPERTIES",
    "  Trichotomy: a<b,a=b, or a>b",
    "  Trans: a<b,b<c => a<c",
    "",
    "  Mult Prop of Order:",
    "  c>0: a<b => ac<bc",
    "  c<0: a<b => ac>bc (FLIP!)",
    "  c=0: ac=bc=0",
    "",
    "ZERO/ONE PROPS",
    "  a*0 = 0",
    "  -(-a) = a",
    "  (-a)*b = -(ab)",
    "  (-a)*(-b) = ab",
    "  a/1 = a",
    "",
    "FRACTION PROPS",
    "  (a/b)*(c/d) = ac/bd",
    "  (a/b)+(c/b) = (a+c)/b",
];

pub const QUAD_QUICK_REF: &[&str] = &[
    "=== QUADRATIC QUICK REF ===",
    "",
    "STANDARD FORM",
    "  y = ax^2 + bx + c",
    "  a not 0",
    "",
    "VERTEX FORM",
    "  y = a(x-h)^2 + k",
    "  vertex = (h, k)",
    "  axis: x = h",
    "",
    "COMPLETING THE SQUARE",
    "  Given ax^2+bx+c:",
    "  1. Factor a from x terms",
    "     a(x^2 + (b/a)x) + c",
    "  2. Add/sub (b/2a)^2 inside:",
    "     a(x+b/2a)^2 + c-b^2/4a",
    "  3. h=-b/2a, k=c-b^2/4a",
    "",
    "QUADRATIC FORMULA",
    "  x = (-b +- sqrt(D)) / 2a",
    "  D = b^2-4ac (discriminant)",
    "",
    "COMPLEX ROOTS (D<0)",
    "  x = -b/2a +- (sqrt|D|/2a)i",
    "  Always come in conj pairs",
    "",
    "CONJUGATE MULTIPLY",
    "  (a+bi)(a-bi) = a^2+b^2",
    "  Always a real number!",
    "",
    "COMPLEX DIVISION",
    "  (a+bi)/(c+di)",
    "  = (a+bi)(c-di)/(c^2+d^2)",
];
